package rust

import (
	"bytes"
	"fmt"
	"os/exec"
	"sort"
	"strconv"
	"strings"

	"github.com/Southclaws/schemancer/schemancer/generators"
	"github.com/Southclaws/schemancer/schemancer/generators/casing"
	"github.com/Southclaws/schemancer/schemancer/ir"
)

var DefaultFormatMappings = map[ir.IRFormat]generators.FormatTypeMapping{
	ir.IRFormatByte:     {Type: "Vec<u8>"},
	ir.IRFormatDateTime: {Type: "String"},
	ir.IRFormatDate:     {Type: "String"},
	ir.IRFormatUUID:     {Type: "String"},
	ir.IRFormatEmail:    {Type: "String"},
	ir.IRFormatURI:      {Type: "String"},
}

type config struct {
	filename string
}

type Option struct {
	apply func(*config)
}

func (Option) OptionValue() string { return "rust" }

func WithFilename(filename string) Option {
	return Option{apply: func(config *config) {
		config.filename = filename
	}}
}

type Generator struct{}

func (g *Generator) Generate(data *ir.IR, opts generators.GeneratorOptions, genOpts ...generators.GeneratorOption) ([]generators.GeneratedFile, error) {
	cfg := config{filename: "types.rs"}
	for _, opt := range genOpts {
		if rustOpt, ok := opt.(Option); ok {
			rustOpt.apply(&cfg)
		}
	}
	if cfg.filename == "" {
		return nil, fmt.Errorf("Rust output filename cannot be empty")
	}

	formatMappings := make(map[ir.IRFormat]generators.FormatTypeMapping, len(DefaultFormatMappings)+len(opts.FormatMappings))
	for format, mapping := range DefaultFormatMappings {
		formatMappings[format] = mapping
	}
	for format, mapping := range opts.FormatMappings {
		formatMappings[format] = mapping
	}

	renderer := renderer{formatMappings: formatMappings}
	content, err := formatRust([]byte(renderer.render(data)))
	if err != nil {
		return nil, err
	}
	return []generators.GeneratedFile{{Filename: cfg.filename, Content: content}}, nil
}

func formatRust(source []byte) ([]byte, error) {
	command := exec.Command("rustfmt", "--emit", "stdout", "--edition", "2024")
	command.Stdin = bytes.NewReader(source)
	var stderr bytes.Buffer
	command.Stderr = &stderr
	formatted, err := command.Output()
	if err != nil {
		return nil, fmt.Errorf("format generated Rust: %w: %s", err, strings.TrimSpace(stderr.String()))
	}
	return formatted, nil
}

type renderer struct {
	formatMappings map[ir.IRFormat]generators.FormatTypeMapping
}

func (r renderer) render(data *ir.IR) string {
	var output strings.Builder
	output.WriteString("// Code generated by Schemancer. DO NOT EDIT.\n\n")

	imports := r.collectImports(data.Types)
	for _, importPath := range imports {
		output.WriteString("use ")
		output.WriteString(importPath)
		output.WriteString(";\n")
	}
	output.WriteString("\n")
	output.WriteString(optionalTypes)
	for _, enumType := range r.collectInlineEnums(data.Types) {
		output.WriteString("\n")
		r.renderEnum(&output, enumType)
	}

	for _, schemaType := range data.Types {
		output.WriteString("\n")
		r.renderType(&output, schemaType)
	}

	return output.String()
}

func (r renderer) collectInlineEnums(types []ir.IRType) []ir.IRType {
	enums := make(map[string]ir.IRType)
	var collectRef func(*ir.IRTypeRef)
	collectRef = func(ref *ir.IRTypeRef) {
		if ref == nil {
			return
		}
		if ref.EnumName != "" {
			enums[ref.EnumName] = ir.IRType{
				Name:       ref.EnumName,
				Kind:       ir.IRKindEnum,
				EnumValues: ref.EnumValues,
				EnumType:   ref.EnumType,
			}
		}
		collectRef(ref.Array)
		collectRef(ref.Map)
	}
	for _, schemaType := range types {
		collectRef(schemaType.Element)
		for index := range schemaType.Fields {
			collectRef(&schemaType.Fields[index].Type)
		}
		if schemaType.Union != nil {
			for _, variant := range schemaType.Union.Variants {
				for index := range variant.Type.Fields {
					collectRef(&variant.Type.Fields[index].Type)
				}
			}
		}
	}

	names := make([]string, 0, len(enums))
	for name := range enums {
		names = append(names, name)
	}
	sort.Strings(names)
	result := make([]ir.IRType, 0, len(names))
	for _, name := range names {
		result = append(result, enums[name])
	}
	return result
}

func (r renderer) collectImports(types []ir.IRType) []string {
	imports := map[string]struct{}{
		"serde::{Deserialize, Deserializer, Serialize, Serializer}": {},
	}
	var collectRef func(*ir.IRTypeRef)
	collectRef = func(ref *ir.IRTypeRef) {
		if ref == nil {
			return
		}
		if mapping, ok := r.formatMappings[ref.Format]; ok && mapping.Import != "" {
			imports[mapping.Import] = struct{}{}
		} else if ref.Builtin == ir.IRBuiltinAny {
			imports["serde_json::Value"] = struct{}{}
		}
		if ref.Array != nil {
			collectRef(ref.Array)
		}
		if ref.Map != nil {
			imports["std::collections::BTreeMap"] = struct{}{}
			collectRef(ref.Map)
		}
	}

	for _, schemaType := range types {
		if schemaType.Union != nil {
			imports["serde_json::value::RawValue"] = struct{}{}
		}
		collectRef(schemaType.Element)
		for index := range schemaType.Fields {
			collectRef(&schemaType.Fields[index].Type)
		}
		if schemaType.Union != nil {
			for _, variant := range schemaType.Union.Variants {
				for index := range variant.Type.Fields {
					collectRef(&variant.Type.Fields[index].Type)
				}
			}
		}
		if schemaType.SimpleUnion != nil {
			for index := range schemaType.SimpleUnion.Variants {
				collectRef(&schemaType.SimpleUnion.Variants[index])
			}
		}
	}

	result := make([]string, 0, len(imports))
	for importPath := range imports {
		result = append(result, importPath)
	}
	sort.Strings(result)
	return result
}

func (r renderer) renderType(output *strings.Builder, schemaType ir.IRType) {
	r.writeDoc(output, schemaType.Description, "")
	switch schemaType.Kind {
	case ir.IRKindStruct:
		r.renderStruct(output, schemaType.Name, schemaType.Fields, schemaType.DenyUnknownFields)
	case ir.IRKindAlias:
		output.WriteString("pub type ")
		output.WriteString(schemaType.Name)
		output.WriteString(" = ")
		output.WriteString(r.typeRef(schemaType.Element, true))
		output.WriteString(";\n")
	case ir.IRKindEnum:
		r.renderEnum(output, schemaType)
	case ir.IRKindDiscriminatedUnion:
		r.renderDiscriminatedUnion(output, schemaType)
	case ir.IRKindUnion:
		r.renderSimpleUnion(output, schemaType)
	}
}

func (r renderer) renderStruct(output *strings.Builder, name string, fields []ir.IRField, denyUnknown bool) {
	output.WriteString("#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n")
	if denyUnknown {
		output.WriteString("#[serde(deny_unknown_fields)]\n")
	}
	output.WriteString("pub struct ")
	output.WriteString(name)
	if len(fields) == 0 {
		output.WriteString(" {}\n")
		return
	}
	output.WriteString(" {\n")
	for _, field := range fields {
		r.renderField(output, field, "    ")
	}
	output.WriteString("}\n")
}

func (r renderer) renderField(output *strings.Builder, field ir.IRField, indent string) {
	r.writeDoc(output, field.Description, indent)
	if !field.Required {
		output.WriteString(indent)
		output.WriteString("#[serde(\n")
		output.WriteString(indent)
		output.WriteString("    rename = ")
		output.WriteString(strconv.Quote(field.JSONName))
		output.WriteString(",\n")
		output.WriteString(indent)
		output.WriteString("    default,\n")
		output.WriteString(indent)
		output.WriteString("    skip_serializing_if = \"OptionalField::is_missing\"\n")
		output.WriteString(indent)
		output.WriteString(")]\n")
	} else {
		output.WriteString(indent)
		output.WriteString("#[serde(rename = ")
		output.WriteString(strconv.Quote(field.JSONName))
		output.WriteString(")]\n")
	}
	output.WriteString(indent)
	output.WriteString("pub ")
	output.WriteString(rustFieldName(field.JSONName))
	output.WriteString(": ")
	output.WriteString(r.typeRef(&field.Type, field.Required))
	output.WriteString(",\n")
}

func (r renderer) renderEnum(output *strings.Builder, schemaType ir.IRType) {
	if schemaType.EnumType == ir.IRBuiltinInt {
		r.renderIntegerEnum(output, schemaType)
		return
	}

	output.WriteString("#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]\n")
	output.WriteString("pub enum ")
	output.WriteString(schemaType.Name)
	output.WriteString(" {\n")
	for _, value := range schemaType.EnumValues {
		if value.IsNull {
			continue
		}
		output.WriteString("    #[serde(rename = ")
		output.WriteString(strconv.Quote(value.StringValue))
		output.WriteString(")]\n    ")
		output.WriteString(rustVariantName(value.StringValue))
		output.WriteString(",\n")
	}
	output.WriteString("}\n")
}

func (r renderer) renderIntegerEnum(output *strings.Builder, schemaType ir.IRType) {
	output.WriteString("#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]\n")
	output.WriteString("#[repr(i64)]\n#[serde(try_from = \"i64\", into = \"i64\")]\n")
	output.WriteString("pub enum ")
	output.WriteString(schemaType.Name)
	output.WriteString(" {\n")
	for _, value := range schemaType.EnumValues {
		if value.IsNull || value.IntValue == nil {
			continue
		}
		output.WriteString("    N")
		output.WriteString(strings.ReplaceAll(value.StringValue, "-", "Negative"))
		output.WriteString(" = ")
		output.WriteString(strconv.Itoa(*value.IntValue))
		output.WriteString(",\n")
	}
	output.WriteString("}\n\n")
	output.WriteString("impl TryFrom<i64> for ")
	output.WriteString(schemaType.Name)
	output.WriteString(" {\n    type Error = String;\n\n    fn try_from(value: i64) -> Result<Self, Self::Error> {\n        match value {\n")
	for _, value := range schemaType.EnumValues {
		if value.IsNull || value.IntValue == nil {
			continue
		}
		output.WriteString("            ")
		output.WriteString(strconv.Itoa(*value.IntValue))
		output.WriteString(" => Ok(Self::N")
		output.WriteString(strings.ReplaceAll(value.StringValue, "-", "Negative"))
		output.WriteString("),\n")
	}
	output.WriteString("            _ => Err(format!(\"invalid ")
	output.WriteString(schemaType.Name)
	output.WriteString(" value: {value}\")),\n        }\n    }\n}\n\n")
	output.WriteString("impl From<")
	output.WriteString(schemaType.Name)
	output.WriteString("> for i64 {\n    fn from(value: ")
	output.WriteString(schemaType.Name)
	output.WriteString(") -> Self {\n        value as i64\n    }\n}\n")
}

func (r renderer) renderDiscriminatedUnion(output *strings.Builder, schemaType ir.IRType) {
	union := schemaType.Union
	output.WriteString("#[derive(Clone, Debug, PartialEq)]\n")
	output.WriteString("pub enum ")
	output.WriteString(schemaType.Name)
	output.WriteString(" {\n")
	for _, variant := range union.Variants {
		output.WriteString("    ")
		output.WriteString(variant.Name)
		output.WriteString("(Box<")
		output.WriteString(variant.Name)
		output.WriteString(">),\n")
	}
	output.WriteString("}\n")
	r.renderUnionSerialize(output, schemaType)
	r.renderUnionDeserialize(output, schemaType)

	for _, variant := range union.Variants {
		output.WriteString("\n")
		r.writeDoc(output, variant.Type.Description, "")
		fields := make([]ir.IRField, 0, len(variant.Type.Fields)-1)
		for _, field := range variant.Type.Fields {
			if field.JSONName != union.DiscriminatorJSON {
				fields = append(fields, field)
			}
		}
		r.renderUnionPayload(output, variant.Name, fields)
		output.WriteString("\n")
		r.renderUnionWireTypes(output, variant, fields)
	}
}

func (r renderer) renderUnionSerialize(output *strings.Builder, schemaType ir.IRType) {
	output.WriteString("\nimpl Serialize for ")
	output.WriteString(schemaType.Name)
	output.WriteString(" {\n")
	output.WriteString("    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {\n")
	output.WriteString("        match self {\n")
	for _, variant := range schemaType.Union.Variants {
		fields := fieldsWithoutDiscriminator(variant.Type.Fields, schemaType.Union.DiscriminatorJSON)
		output.WriteString("            Self::")
		output.WriteString(variant.Name)
		if len(fields) == 0 {
			output.WriteString("(_value) => ")
		} else {
			output.WriteString("(value) => ")
		}
		output.WriteString(variant.Name)
		output.WriteString("WireRef {\n                kind: ")
		output.WriteString(variant.Name)
		output.WriteString("Tag::Value,\n")
		for _, field := range fields {
			output.WriteString("                ")
			output.WriteString(rustFieldName(field.JSONName))
			output.WriteString(": &value.")
			output.WriteString(rustFieldName(field.JSONName))
			output.WriteString(",\n")
		}
		output.WriteString("            }\n            .serialize(serializer),\n")
	}
	output.WriteString("        }\n    }\n}\n")
}

func (r renderer) renderUnionDeserialize(output *strings.Builder, schemaType ir.IRType) {
	union := schemaType.Union
	output.WriteString("\nimpl<'de> Deserialize<'de> for ")
	output.WriteString(schemaType.Name)
	output.WriteString(" {\n")
	output.WriteString("    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {\n")
	output.WriteString("        #[derive(Deserialize)]\n")
	output.WriteString("        struct Discriminator {\n")
	output.WriteString("            #[serde(rename = ")
	output.WriteString(strconv.Quote(union.DiscriminatorJSON))
	output.WriteString(")]\n            value: String,\n        }\n\n")
	output.WriteString("        let raw = Box::<RawValue>::deserialize(deserializer)?;\n")
	output.WriteString("        let discriminator: Discriminator = serde_json::from_str(raw.get())\n")
	output.WriteString("            .map_err(serde::de::Error::custom)?;\n")
	output.WriteString("        match discriminator.value.as_str() {\n")
	for _, variant := range union.Variants {
		fields := fieldsWithoutDiscriminator(variant.Type.Fields, union.DiscriminatorJSON)
		output.WriteString("            ")
		output.WriteString(strconv.Quote(variant.ConstValue))
		output.WriteString(" => {\n                let wire: ")
		output.WriteString(variant.Name)
		output.WriteString("Wire = serde_json::from_str(raw.get())\n")
		output.WriteString("                    .map_err(serde::de::Error::custom)?;\n")
		if len(fields) == 0 {
			output.WriteString("                let _ = wire._kind;\n")
		}
		output.WriteString("                Ok(Self::")
		output.WriteString(variant.Name)
		output.WriteString("(Box::new(")
		output.WriteString(variant.Name)
		output.WriteString(" {\n")
		for _, field := range fields {
			name := rustFieldName(field.JSONName)
			output.WriteString("                    ")
			output.WriteString(name)
			output.WriteString(": wire.")
			output.WriteString(name)
			output.WriteString(",\n")
		}
		output.WriteString("                })))\n            }\n")
	}
	output.WriteString("            value => Err(serde::de::Error::custom(format!(\"")
	output.WriteString(schemaType.Name)
	output.WriteString(": unknown ")
	output.WriteString(union.DiscriminatorJSON)
	output.WriteString(" {value:?}\"))),\n")
	output.WriteString("        }\n    }\n}\n")
}

func (r renderer) renderUnionPayload(output *strings.Builder, name string, fields []ir.IRField) {
	output.WriteString("#[derive(Clone, Debug, PartialEq)]\n")
	output.WriteString("pub struct ")
	output.WriteString(name)
	if len(fields) == 0 {
		output.WriteString(" {}\n")
		return
	}
	output.WriteString(" {\n")
	for _, field := range fields {
		r.writeDoc(output, field.Description, "    ")
		output.WriteString("    pub ")
		output.WriteString(rustFieldName(field.JSONName))
		output.WriteString(": ")
		output.WriteString(r.typeRef(&field.Type, field.Required))
		output.WriteString(",\n")
	}
	output.WriteString("}\n")
}

func (r renderer) renderUnionWireTypes(output *strings.Builder, variant ir.IRVariant, fields []ir.IRField) {
	output.WriteString("#[derive(Clone, Copy, Serialize, Deserialize)]\n")
	output.WriteString("enum ")
	output.WriteString(variant.Name)
	output.WriteString("Tag {\n    #[serde(rename = ")
	output.WriteString(strconv.Quote(variant.ConstValue))
	output.WriteString(")]\n    Value,\n}\n\n")

	output.WriteString("#[derive(Deserialize)]\n")
	if variant.Type.DenyUnknownFields {
		output.WriteString("#[serde(deny_unknown_fields)]\n")
	}
	output.WriteString("struct ")
	output.WriteString(variant.Name)
	output.WriteString("Wire {\n    #[serde(rename = ")
	output.WriteString(strconv.Quote(findDiscriminatorJSONName(variant.Type.Fields)))
	output.WriteString(")]\n    _kind: ")
	output.WriteString(variant.Name)
	output.WriteString("Tag,\n")
	for _, field := range fields {
		r.renderPrivateWireField(output, field, "    ", false)
	}
	output.WriteString("}\n\n")

	output.WriteString("#[derive(Serialize)]\nstruct ")
	output.WriteString(variant.Name)
	if len(fields) == 0 {
		output.WriteString("WireRef {\n    #[serde(rename = ")
	} else {
		output.WriteString("WireRef<'a> {\n    #[serde(rename = ")
	}
	output.WriteString(strconv.Quote(findDiscriminatorJSONName(variant.Type.Fields)))
	output.WriteString(")]\n    kind: ")
	output.WriteString(variant.Name)
	output.WriteString("Tag,\n")
	for _, field := range fields {
		r.renderPrivateWireField(output, field, "    ", true)
	}
	output.WriteString("}\n")
}

func (r renderer) renderPrivateWireField(output *strings.Builder, field ir.IRField, indent string, byReference bool) {
	if !field.Required {
		output.WriteString(indent)
		output.WriteString("#[serde(\n")
		output.WriteString(indent)
		output.WriteString("    rename = ")
		output.WriteString(strconv.Quote(field.JSONName))
		output.WriteString(",\n")
		if !byReference {
			output.WriteString(indent)
			output.WriteString("    default,\n")
		} else {
			output.WriteString(indent)
			output.WriteString("    skip_serializing_if = \"OptionalField::is_missing\"\n")
		}
		output.WriteString(indent)
		output.WriteString(")]\n")
	} else {
		output.WriteString(indent)
		output.WriteString("#[serde(rename = ")
		output.WriteString(strconv.Quote(field.JSONName))
		output.WriteString(")]\n")
	}
	output.WriteString(indent)
	output.WriteString(rustFieldName(field.JSONName))
	output.WriteString(": ")
	if byReference {
		output.WriteString("&'a ")
	}
	output.WriteString(r.typeRef(&field.Type, field.Required))
	output.WriteString(",\n")
}

func fieldsWithoutDiscriminator(fields []ir.IRField, discriminatorJSON string) []ir.IRField {
	result := make([]ir.IRField, 0, len(fields)-1)
	for _, field := range fields {
		if field.JSONName != discriminatorJSON {
			result = append(result, field)
		}
	}
	return result
}

func findDiscriminatorJSONName(fields []ir.IRField) string {
	for _, field := range fields {
		if field.Type.Builtin == ir.IRBuiltinString && field.Required {
			if field.JSONName == "kind" || field.JSONName == "type" {
				return field.JSONName
			}
		}
	}
	return "kind"
}

func (r renderer) renderSimpleUnion(output *strings.Builder, schemaType ir.IRType) {
	output.WriteString("#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n")
	output.WriteString("#[serde(untagged)]\n")
	output.WriteString("pub enum ")
	output.WriteString(schemaType.Name)
	output.WriteString(" {\n")
	usedNames := make(map[string]int)
	for index := range schemaType.SimpleUnion.Variants {
		variant := &schemaType.SimpleUnion.Variants[index]
		name := r.unionVariantName(variant)
		usedNames[name]++
		if usedNames[name] > 1 {
			name += strconv.Itoa(usedNames[name])
		}
		output.WriteString("    ")
		output.WriteString(name)
		if variant.Nullable && variant.Builtin == ir.IRBuiltinAny {
			output.WriteString(",\n")
		} else {
			output.WriteString("(")
			output.WriteString(r.typeRef(variant, true))
			output.WriteString("),\n")
		}
	}
	output.WriteString("}\n")
}

func (r renderer) unionVariantName(ref *ir.IRTypeRef) string {
	if ref.Name != "" {
		return ref.Name
	}
	if ref.Array != nil {
		return "Array"
	}
	if ref.Map != nil {
		return "Object"
	}
	switch ref.Builtin {
	case ir.IRBuiltinString:
		return "String"
	case ir.IRBuiltinInt:
		return "Integer"
	case ir.IRBuiltinFloat:
		return "Number"
	case ir.IRBuiltinBool:
		return "Boolean"
	default:
		if ref.Nullable {
			return "Null"
		}
		return "Any"
	}
}

func (r renderer) typeRef(ref *ir.IRTypeRef, required bool) string {
	if ref == nil {
		return "Value"
	}

	base := ""
	if mapping, ok := r.formatMappings[ref.Format]; ok {
		base = mapping.Type
	}
	if base == "" {
		switch {
		case ref.EnumName != "":
			base = ref.EnumName
		case ref.Array != nil:
			base = "Vec<" + r.typeRef(ref.Array, true) + ">"
		case ref.Map != nil:
			base = "BTreeMap<String, " + r.typeRef(ref.Map, true) + ">"
		case ref.Name != "":
			base = ref.Name
		default:
			switch ref.Builtin {
			case ir.IRBuiltinString:
				base = "String"
			case ir.IRBuiltinInt:
				base = "i64"
			case ir.IRBuiltinFloat:
				base = "f64"
			case ir.IRBuiltinBool:
				base = "bool"
			default:
				base = "Value"
			}
		}
	}

	if ref.Nullable {
		base = "Nullable<" + base + ">"
	}
	if !required {
		base = "OptionalField<" + base + ">"
	}
	return base
}

func (r renderer) writeDoc(output *strings.Builder, description, indent string) {
	if description == "" {
		return
	}
	for _, line := range strings.Split(strings.TrimSuffix(description, "\n"), "\n") {
		output.WriteString(indent)
		output.WriteString("///")
		if line != "" {
			output.WriteString(" ")
			output.WriteString(line)
		}
		output.WriteString("\n")
	}
}

func rustFieldName(jsonName string) string {
	name := casing.ToSnakeCase(jsonName)
	if name == "" {
		return "field"
	}
	if name[0] >= '0' && name[0] <= '9' {
		name = "n_" + name
	}
	if rustKeywords[name] {
		return "r#" + name
	}
	return name
}

func rustVariantName(value string) string {
	name := casing.ToPascalCase(value)
	if name == "" {
		return "Empty"
	}
	if name[0] >= '0' && name[0] <= '9' {
		return "N" + name
	}
	return name
}

var rustKeywords = map[string]bool{
	"as": true, "async": true, "await": true, "break": true, "const": true,
	"continue": true, "crate": true, "dyn": true, "else": true, "enum": true,
	"extern": true, "false": true, "final": true, "fn": true, "for": true,
	"if": true, "impl": true, "in": true, "let": true, "loop": true,
	"macro": true, "match": true, "mod": true, "move": true, "mut": true,
	"override": true, "priv": true, "pub": true, "ref": true, "return": true,
	"self": true, "static": true, "struct": true, "super": true, "trait": true,
	"true": true, "try": true, "type": true, "typeof": true, "union": true,
	"unsafe": true, "unsized": true, "use": true, "virtual": true, "where": true,
	"while": true, "yield": true,
}

const optionalTypes = `/// A field that distinguishes omission from an explicitly provided value.
#[derive(Clone, Debug, Default, PartialEq)]
pub enum OptionalField<T> {
    #[default]
    Missing,
    Present(T),
}

impl<T> OptionalField<T> {
    pub fn is_missing(&self) -> bool {
        matches!(self, Self::Missing)
    }

    pub fn as_ref(&self) -> OptionalField<&T> {
        match self {
            Self::Missing => OptionalField::Missing,
            Self::Present(value) => OptionalField::Present(value),
        }
    }
}

impl<T: Serialize> Serialize for OptionalField<T> {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Missing => serializer.serialize_none(),
            Self::Present(value) => value.serialize(serializer),
        }
    }
}

impl<'de, T: Deserialize<'de>> Deserialize<'de> for OptionalField<T> {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        T::deserialize(deserializer).map(Self::Present)
    }
}

/// A required or present field whose JSON value may explicitly be null.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Nullable<T>(pub Option<T>);

impl<T> Nullable<T> {
    pub fn null() -> Self {
        Self(None)
    }

    pub fn value(value: T) -> Self {
        Self(Some(value))
    }

    pub fn as_ref(&self) -> Option<&T> {
        self.0.as_ref()
    }
}

impl<T: Serialize> Serialize for Nullable<T> {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        self.0.serialize(serializer)
    }
}

impl<'de, T: Deserialize<'de>> Deserialize<'de> for Nullable<T> {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Option::<T>::deserialize(deserializer).map(Self)
    }
}
`
